In [1]:
import pandas as pd
import numpy as np

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns


C:\Users\abhin\anaconda3\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [3]:
df=pd.read_csv('boston.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64  
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64  
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB


In [4]:
x=df.drop('MEDV',axis =1)
x

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273.0   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273.0   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273.0   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273.0   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [5]:
y=df['MEDV']
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: MEDV, Length: 506, dtype: float64

In [6]:
from sklearn.preprocessing import StandardScaler

In [7]:
scaler = StandardScaler()

In [8]:
x_scale = scaler.fit_transform(x)

In [9]:
x_scale

array([[-0.41978194,  0.28482986, -1.2879095 , ..., -1.45900038,
         0.44105193, -1.0755623 ],
       [-0.41733926, -0.48772236, -0.59338101, ..., -0.30309415,
         0.44105193, -0.49243937],
       [-0.41734159, -0.48772236, -0.59338101, ..., -0.30309415,
         0.39642699, -1.2087274 ],
       ...,
       [-0.41344658, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.98304761],
       [-0.40776407, -0.48772236,  0.11573841, ...,  1.17646583,
         0.4032249 , -0.86530163],
       [-0.41500016, -0.48772236,  0.11573841, ...,  1.17646583,
         0.44105193, -0.66905833]])

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x_scale, y, test_size=0.18, random_state=18)

In [11]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train,y_train)

LinearRegression()

In [12]:
y_pred=model.predict(X_test)

In [13]:
y_pred

array([32.69106094, 10.98396688, 25.08566149, 34.37017459, 16.27639885,
       20.98959208, 35.40904372, 39.17680012, 37.42903027, 28.49293636,
       20.27206714, 17.8440723 , 36.41360261, 24.51098953, 15.00159628,
       25.19869449, 18.09978504, 33.24598345, 32.33437935, 27.59217649,
       31.2223058 , 16.46649125, 21.51205405, 31.08751713, 25.61285625,
       20.06530175, 20.55007157,  9.51186203, 31.07431159, 13.27785252,
       32.47887953, 20.38013817, 22.76972363,  2.42934734, 18.69387813,
        7.24576006, 25.71112995, 20.18308437,  2.57087777,  8.8800766 ,
       22.5717724 , 37.73260091, 22.14683158, 12.84005232, 29.30936024,
       15.08433151, 10.90243714, 17.79322044,  5.6195855 , 23.15346062,
       18.33150201, 12.68268595, 11.02466423, 19.36848055, 31.42249874,
       32.67389031, 24.38512772, 19.68116689, 21.8707815 , 25.54986824,
       36.74613813, 19.47431485, 23.56990508, 17.63322974, 13.1366849 ,
       25.00581315, 30.1280703 , 16.30344873, 19.93077577, 16.65

In [14]:
from sklearn.metrics import mean_squared_error, r2_score,mean_absolute_error

predictions = model.predict(X_test)

mse = mean_squared_error(y_test, predictions)
r2 = r2_score(y_test, predictions)
mab = mean_absolute_error(y_test, predictions)

print("Mean Squared Error: ", mse)
print("R-squared (R2): ", r2)
print("Mean Absolute Error : ", mab)

Mean Squared Error:  28.45588932633132
R-squared (R2):  0.6738697447005217
Mean Absolute Error :  3.620283356389151


In [15]:
import tensorflow as tf

In [16]:
predictions

array([32.69106094, 10.98396688, 25.08566149, 34.37017459, 16.27639885,
       20.98959208, 35.40904372, 39.17680012, 37.42903027, 28.49293636,
       20.27206714, 17.8440723 , 36.41360261, 24.51098953, 15.00159628,
       25.19869449, 18.09978504, 33.24598345, 32.33437935, 27.59217649,
       31.2223058 , 16.46649125, 21.51205405, 31.08751713, 25.61285625,
       20.06530175, 20.55007157,  9.51186203, 31.07431159, 13.27785252,
       32.47887953, 20.38013817, 22.76972363,  2.42934734, 18.69387813,
        7.24576006, 25.71112995, 20.18308437,  2.57087777,  8.8800766 ,
       22.5717724 , 37.73260091, 22.14683158, 12.84005232, 29.30936024,
       15.08433151, 10.90243714, 17.79322044,  5.6195855 , 23.15346062,
       18.33150201, 12.68268595, 11.02466423, 19.36848055, 31.42249874,
       32.67389031, 24.38512772, 19.68116689, 21.8707815 , 25.54986824,
       36.74613813, 19.47431485, 23.56990508, 17.63322974, 13.1366849 ,
       25.00581315, 30.1280703 , 16.30344873, 19.93077577, 16.65

In [17]:
tf

<module 'tensorflow' from 'C:\\Users\\abhin\\anaconda3\\lib\\site-packages\\tensorflow\\__init__.py'>

In [18]:
X_train.shape[1]

13

In [19]:
X_train.shape

(414, 13)

In [20]:
model=tf.keras.Sequential([
    tf.keras.layers.Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(32, activation='relu',),
    tf.keras.layers.Dense(16, activation='relu',),
    tf.keras.layers.Dense(1)
    
])

C:\Users\abhin\anaconda3\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [21]:
model

<Sequential name=sequential, built=True>

In [22]:
model.compile(optimizer='adam',loss='mean_squared_error')

In [23]:
model.fit(X_train,y_train,epochs=100,batch_size=32,validation_data=(X_test,y_test))

Epoch 1/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - loss: 533.3646 - val_loss: 561.1827
Epoch 2/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 542.5547 - val_loss: 498.7747
Epoch 3/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 474.1228 - val_loss: 400.5926
Epoch 4/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 332.2731 - val_loss: 269.6566
Epoch 5/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 184.8840 - val_loss: 145.8306
Epoch 6/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 103.5842 - val_loss: 93.0616
Epoch 7/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 77.2316 - val_loss: 71.3452
Epoch 8/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 47.5995 - val_loss: 57.1905
Epoch 9/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 39.4505 - val_loss: 45.4108
Epoch 10/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 32.3721 - val_loss: 38.5710
Epoch 11/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 30.4751 - val_loss: 33.9631
Epoch 12/100
13/13 ━━━━━━━━━━

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5.9575 - val_loss: 14.4442
Epoch 69/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.9143 - val_loss: 14.3071
Epoch 70/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.4436 - val_loss: 14.4918
Epoch 71/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.9892 - val_loss: 14.2583
Epoch 72/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.9092 - val_loss: 14.5844
Epoch 73/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.5558 - val_loss: 14.1314
Epoch 74/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 7.4142 - val_loss: 14.4082
Epoch 75/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.0614 - val_loss: 14.0507
Epoch 76/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 6.8282 - val_loss: 14.4214
Epoch 77/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.5653 - val_loss: 13.9965
Epoch 78/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4.9418 - val_loss: 14.4345
Epoch 79/100
13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - lo

In [24]:
loss=model.evaluate(X_test,y_test)

3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 0s/step - loss: 16.4242  


In [25]:
print(f"mse of test data = {loss}")

mse of test data = 14.183304786682129
